### ISSUE TITLE
The method isSticky() is undefined for the type Chunk	TickChunksPlugin.java

### ISSUE THREAD

**Issue by WoutervanderLoopNL** [axeluhl/TickChunks#1]
Hello. 

ive builded the Spigot jar, with the 3747 patch, that succeed. 
ive imported the project in Eclypse and added the spigot jar to the library.

i cant built the Plugin, get an error:
`Description	Resource	Path	Location	Type
The method isSticky() is undefined for the type Chunk	TickChunksPlugin.java	/TickChunks/src/uhl/mc/tickchunks	line 41	Java Problem
`

do you know how to solve it?

**Comment by axeluhl** [comment]
Hi @hermandelul, thanks for trying to get the plug-in. I've added spigot-api to the project dependencies of the plug-in project. See screenshot.
![screenshot from 2018-02-09 23-23-28](https://user-images.githubusercontent.com/483006/36053112-972a579a-0df0-11e8-9d3e-cb24334c35f2.png)
Please make sure that your Chunk.java has the isSticky() method. It should look like this:

    /**
     * @return {@code true} whether this player chunk will remain loaded even if it has no player associated anymore
     */
    boolean isSticky();

**Comment by WoutervanderLoopNL** [comment]
do i need to add this manualy? because the isSticky() and the setSticky() functions arent in the patchfiles of 3747 the setSticky() also gives an error.

i can manually add it to the file. in the build path, but than it isnt on the Spigot.jar right? it should be there to?

**Comment by axeluhl** [comment]
Please make sure you get the SPIGOT-3747 branches of the respective repos:
 - https://hub.spigotmc.org/stash/users/donaldduck70/repos/bukkit/browse?at=refs%2Fheads%2FSPIGOT-3747
 - https://hub.spigotmc.org/stash/users/donaldduck70/repos/craftbukkit/browse?at=refs%2Fheads%2FSPIGOT-3747
 - https://hub.spigotmc.org/stash/users/donaldduck70/repos/spigot/browse?at=refs%2Fheads%2FSPIGOT-3747

Note in particular the diff in the Bukkit repo:
https://hub.spigotmc.org/stash/users/donaldduck70/repos/bukkit/compare/diff?targetBranch=refs%2Fheads%2Fmaster&sourceBranch=refs%2Fheads%2FSPIGOT-3747&targetRepoId=11#src/main/java/org/bukkit/Chunk.java
and the corresponding CraftBukkit patches
https://hub.spigotmc.org/stash/users/donaldduck70/repos/craftbukkit/compare/diff?targetBranch=refs%2Fheads%2Fmaster&sourceBranch=refs%2Fheads%2FSPIGOT-3747&targetRepoId=12#nms-patches/Chunk.patch
The Spigot patches can be seen here:
https://hub.spigotmc.org/stash/users/donaldduck70/repos/spigot/compare/diff?targetBranch=refs%2Fheads%2Fmaster&sourceBranch=refs%2Fheads%2FSPIGOT-3747&targetRepoId=13#CraftBukkit-Patches/0133-Don-t-tick-blocks-if-neighbor-chunks-aren-t-loaded.patch
Hope this helps.

**Comment by WoutervanderLoopNL** [comment]
hallo, i havent access to bitbuckit when i try to login at that link

**Comment by axeluhl** [comment]
I've tried to update https://github.com/axeluhl/TickChunks/blob/master/README.md now and have pushed my Stash repos to Github, too. Hope that helps.

**Comment by axeluhl** [comment]
Sorry, tried rebuilding it myself. You're right. It just doesn't work. I'll try restoring the branches so that things work again. Probably some incompatible changes on the master branch.

**Comment by WoutervanderLoopNL** [comment]
thank you, i will check it out this evening. thanks for the help sofar

**Comment by WoutervanderLoopNL** [comment]
hello, 

ive tried it again on an new clean folder, and get 2 errors:
`$ git fetch origin master:master
fatal: Refusing to fetch into current branch refs/heads/master of non-bare repository`
in the Bukkit and Craftbukkit directory.

when skipping those errors i get an error with the build of the spigot jar
`
HEAD is now at 3ea0bf74 CraftBukkit $ Mon Feb 12 10:53:41 CET 2018
Cloning into 'Spigot-Server'...
done.
Resetting Spigot-Server to CraftBukkit...
fatal: No such remote: upstream
HEAD is now at 3ea0bf74 CraftBukkit $ Mon Feb 12 10:53:41 CET 2018
  Applying patches to Spigot-Server...
fatal: Resolve operation not in progress, we are not resuming.
Applying: POM Changes
Applying: Skeleton API Implementations
Applying: mc-dev imports
Applying: Obfuscation Helpers
error: sha1 information is lacking or useless (src/main/java/net/minecraft/serve                                      r/MinecraftServer.java).
error: could not build fake ancestorPatch failed at 0004 Obfuscation Helpers

The copy of the patch that failed is found in: .git/rebase-apply/patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
  Something did not apply cleanly to Spigot-Server.
  Please review above details and finish the apply then
  save the changes with rebuildPatches.sh
Error compiling Spigot. Please check the wiki for FAQs.
If this does not resolve your issue then please pastebin the entire BuildTools.l                                      og.txt file when seeking support.
java.lang.RuntimeException: Error running command, return status !=0: [sh, apply                                      Patches.sh]
        at org.spigotmc.builder.Builder.runProcess0(Builder.java:639)
        at org.spigotmc.builder.Builder.runProcess(Builder.java:597)
        at org.spigotmc.builder.Builder.main(Builder.java:478)
        at org.spigotmc.builder.Bootstrap.main(Bootstrap.java:23)
`

**Comment by WoutervanderLoopNL** [comment]
The full log of BuildTools

[BuildTools.log.txt](https://github.com/axeluhl/TickChunks/files/1716110/BuildTools.log.txt)

**Comment by WoutervanderLoopNL** [comment]
nevermind my last 2 comments. it was an known issue with the Git.
https://www.spigotmc.org/wiki/buildtools/#issues-and-common-concerns

`Spigot's applyPatches.sh says "Patch failed at ..."
This occurs on Windows if git's autocrlf is set to false (or unset). To fix, run git config --global --replace-all core.autocrlf true and re-pull/re-run BuildTools
If on linux, run git config --global --unset core.autocrlf and re-pull/re-run BuildTools.`

i will test it further, i will keep you updated

**Comment by WoutervanderLoopNL** [comment]
ive builded Spigot and Created the Plugin jar. 

tested, and it looks likes it works. 

thanks for the help ;-)

**Comment by axeluhl** [comment]
Great! I've been fighting this issue with the crlf thing myself for two days now. Great you found it in the FAQ.

To import all KeepChunks chunks into TickChunks it's probably easiest for now to use a little script that converts your KeepChunks config.

See attached, also now on the master branch in the TickChunks github repository.

**Comment by axeluhl** [comment]
Thanks again. I've updated the readme https://github.com/axeluhl/TickChunks/blob/master/README.md accordingly

**Comment by WoutervanderLoopNL** [comment]
at your services ;-)
