### ISSUE TITLE
Feature to import current KeepChunks chunks to TickChunks

### ISSUE THREAD

**Issue by WoutervanderLoopNL** [axeluhl/TickChunks#2]
Hello. 

is it possible to add an function/command that imports all existing "KeepChunks" chunks to the TickChunks?

ive already an server with a few dozen loaded chunks. want to import them to the TickChunks plugin. 

Thanks Sofar

**Comment by WoutervanderLoopNL** [comment]
Thanks for adding the script. just an bug with it

you have for grep `"^- [0-9-]*#[0-9-]#"` on line 12 and 14, that needs to be `"^- [0-9-]*#[0-9-]*#"`  ;-) 

the * before the last # is required to grep correctly

**Comment by axeluhl** [comment]
Good catch! Thanks for testing this. https://github.com/axeluhl/TickChunks/commit/88f31c4f997b39891b892a561822abcd92f89a46 should fix this.

**Comment by WoutervanderLoopNL** [comment]
Thank you to. Migrated the server, and added the plug-in, all works good. 

Thanks for making the patch and plug-in
